mageck-fdr:
  fdr: 0.25
GO:
  email: "your@email.here" #create an account first on https://david.ncifcrf.gov/webservice/register.htm
  test: "Benjamini" #choose Bonferroni or Benjamini
  term: "BP" #BP, CC or MF
bassik:
  fasta: "/home/niek/Documents/references/fasta/Human/Bassik-library/bassik_lib.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/bassik/bassik"
  read_mod: "clip"
  clip_seq: "GTTTAAGAGCTAAGCTGGAAACAGCATAGCAA"
  sg_length: ""
  species: "human"
moffat_tko1:
  fasta: "/home/niek/Documents/references/fasta/Human/Moffat_TKO1/moffat_tko1.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/moffat_tko1/moffat_tko1"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
moffat_tko3:
  fasta: "/home/niek/Documents/references/fasta/Human/Moffat_TKO3/Moffat_TKO3.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/moffat_tko3/moffat_tko3"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
sabatini:
  fasta: "/home/niek/Documents/references/fasta/Human/Sabatini-library/sabatini-guides.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/sabatini/sabatini"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
dub-only:
  fasta: "/home/niek/Documents/references/fasta/Human/DUB-only/DUBonly.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/dub-only/bowtie2-dub-only-index"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
slc-mito-2ogdd:
  fasta: "/home/niek/Documents/references/fasta/Mouse/Mouse-SLC-Mito-2OGDD/mouse-2-OG-DD-SLC-mitoP-library.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/Mouse-SLC-Mito-2OGDD/mouse_2-OG_DD_SLC_mitoP-lib"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 17
  species: "mouse"
ubiquitome:
  fasta: "/home/niek/Documents/references/fasta/Human/ubiquitome/ubiquitome.fa"
  index_path: "/home/niek/Documents/references/bowtie2-index/ubiquitome/ubquitome-index"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
