bassik:
  fasta: ""
  index_path: "/home/niek/Documents/references/bowtie2-index/bassik/bassik"
  guides: "/home/niek/Documents/references/bowtie-index/CRISPR/Bassik/bowtie-lib/bassik-guides-sorted.csv"
  read_mod: "clip"
  clip_seq: "GTTTAAGAGCTAAGCTGGAAACAGCATAGCAA"
  sg_length: ""
  species: "human"
moffat_tko1:
  fasta: ""
  index_path: "/home/niek/Documents/references/bowtie2-index/moffat_tko1/moffat_tko1"
  guides: "/home/niek/Documents/references/bowtie-index/CRISPR/Moffat_TKO1/moffat-guideslist-sorted.csv"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
moffat_tko3:
  fasta: ""
  index_path: "/home/niek/Documents/references/bowtie2-index/moffat_tko3/moffat_tko3"
  guides: "/home/niek/Documents/references/bowtie2-index/moffat_tko3/Moffat_TKO3-guide-names.csv"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
sabatini:
  fasta: ""
  index_path: "/home/niek/Documents/references/bowtie2-index/sabatini/sabatini"
  guides: "/home/niek/Documents/references/bowtie-index/CRISPR/Sabatini/sabatini-guides-names.csv"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
dub-only:
  fasta: ""
  index_path: "/home/niek/Documents/references/bowtie2-index/dub-only/bowtie2-dub-only-index"
  guides: "/home/niek/Documents/references/bowtie-index/CRISPR/DUB-only-lib/DUBlibrarysgRNAname.csv"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 20
  species: "human"
slc-mito-2ogdd:
  fasta: "/home/niek/Documents/references/fasta/Mouse/Mouse-SLC-Mito-2OGDD/mouse-2-OG-DD-SLC-mitoP-library.fasta"
  index_path: "/home/niek/Documents/references/bowtie2-index/Mouse-SLC-Mito-2OGDD/mouse_2-OG_DD_SLC_mitoP-lib"
  guides: "/home/niek/Documents/references/fasta/Mouse/Mouse-SLC-Mito-2OGDD/mouse-2-OG-DD-SLC-mitoP-library-guide-names.csv"
  read_mod: "trim"
  clip_seq: ""
  sg_length: 17
  species: "mouse"
